version: '3'

services:
  backend:
    build:
      context: Backend
    ports:
      - "8000:8000"
    env_file:
      - Backend/.env_prod
  mongo:
    image: mongo:7.0.2
    ports:
      - "27017:27017"
