---
#################################
#################################
## GitHub Actions ##
#################################
#################################
name: General Workflow

#
# Documentation:
# https://docs.github.com/en/actions/learn-github-actions/workflow-syntax-for-github-actions
#

#############################
# Start the job on all push and pull request #
#############################
on: [push, pull_request]

###############
# Set the Job #
###############
jobs:
  license:
    name: License check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"
          cache: 'pip' # caching pip dependencies
      - name: Install Python Dependencies
        uses: py-actions/py-dependency-install@v4
        with:
          path: "./Backend/requirements.txt"
      - name: Check copyright
        id: license_check_report
        uses: pilosus/action-pip-license-checker@v2
        with:
          requirements: "./Backend/requirements.txt"
          fail: "StrongCopyleft"
          totals: true
          headers: true
      - name: Print copyright report
        if: always()
        run: echo "${{ steps.license_check_report.outputs.report }}"
  build:
    # Name the Job
    name: Lint Code Base and Test Backend
    # Set the agent to run on
    runs-on: ubuntu-latest

    ##################
    # Load all steps #
    ##################
    steps:
      ##########################
      # Checkout the code base #
      ##########################
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          # Full git history is needed to get a proper
          # list of changed files within `super-linter`
          fetch-depth: 0
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"
          cache: 'pip' # caching pip dependencies
      - name: Install Python Dependencies
        uses: py-actions/py-dependency-install@v4
        with:
          path: "./Backend/requirements.txt"
      - name: Start MongoDB
        uses: supercharge/mongodb-github-action@1.10.0
        with:
          mongodb-version: "7.0.2"
      ################################
      # Run Linter against code base #
      ################################
      - name: Lint Code Base
        uses: super-linter/super-linter@v5
        env:
          VALIDATE_ALL_CODEBASE: false
          DEFAULT_BRANCH: main
          VALIDATE_JAVASCRIPT_ES: true
          VALIDATE_PYTHON_BLACK: true
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          LINTER_RULES_PATH: "../../Frontend/src/app/.eslintrc.json"
      - name: Run Backend Tests
        working-directory: "./Backend"
        run: pytest test
        env:
          PASSWORD: ${{ secrets.EMAIL_PASSWORD }}

